In [3]:
import numpy as np
print(np.array([1,2,3,4,5]))
print(np.zeros((3,4) , dtype = int))
print(np.ones((5,5) , dtype=float))
print(np.full((3,5) , 3 , dtype=int))
print(np.arange(0,31,3))
print(np.linspace(0,1,20))
print(np.random.randint(0,10,(3,4))) #0 ile 10 arasında 3,4 lük bir array oluşturdu
print(np.random.normal(5,5,(6,6)))

[1 2 3 4 5]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[ 0  3  6  9 12 15 18 21 24 27 30]
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
[[1 6 3 2]
 [1 8 4 5]
 [9 5 4 7]]
[[ 1.52275356  8.97335954 -0.48786535  1.3111564   6.01043306  5.77087465]
 [ 0.81972014  4.23610699  7.49875781 11.38381226  4.55937533 -3.70506107]
 [12.7712491   9.03149034 -2.60316958  4.56776385  7.19281986  5.94627653]
 [ 1.32442389  5.13469828  1.79682454  9.56543531 -0.06317603  2.83495387]
 [13.66434221  5.2210934   7.1871309   0.17004543  9.69701283  7.26868933]
 [ 9.49483965  0.5200054   9.6049985   6.1692492   2.84467456  9.13959203]]


In [18]:
a=np.random.randint(1,9 ,(1,9))
print(a.ndim)
print(a.reshape(1,9))
a.ndim

2
[[2 3 2 1 7 8 2 5 1]]


2

In [19]:
b=np.arange(1,9)
b.ndim

1

In [22]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])
z=np.array([7,8,9])
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
t=np.array([[1,2,3],
           [4,5,6]])
z=np.array([[7,8,9],
           [10,11,12]])
np.concatenate([t,z])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate([x,y] )

In [27]:
q=np.arange(0,20,2)
np.sort(q)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
m=np.random.normal(20,5 ,(3,3))
np.sort(m, axis=1)

array([[17.7750824 , 19.68851932, 28.15166993],
       [12.63879615, 18.52049302, 21.04238055],
       [ 9.21758643, 13.38240028, 18.23077631]])

In [31]:
np.sort(m , axis=0)

array([[12.63879615,  9.21758643, 17.7750824 ],
       [13.38240028, 18.52049302, 18.23077631],
       [28.15166993, 19.68851932, 21.04238055]])

In [37]:
x=np.array([1,2,3,99,99,3,2,1])
a,b,c=np.split(x, [3,5])
#iki boyutlu ayırma
m=np.arange(16).reshape(4,4)
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [34]:
np.hsplit(m, [2])


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]